services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.85.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
      - "9464:9464"    # Prometheus scrape (Collector metrics)
    networks:
      - observability-net

  grafana:
    image: grafana/grafana:latest
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - observability-net

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "3200:3200"   # API HTTP
    networks:
      - observability-net

networks:
  observability-net:
    driver: bridge
