services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: pbuser
      POSTGRES_PASSWORD: pbpasswd
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - pb-net

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pb-net

networks:
  pb-net:
    driver: bridge
